server:
  port: 9001

spring:
  application:
    name: SERVICE_GATEWAY
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/h2
    validate-migration-naming: true

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/payment_db?authSource=admin

    redis:
      lettuce:
        pool:
          enabled: true
      host: localhost
      port: 7000
      password:
      timeout: 5000ms
      database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: contractlens_user
    password: contractlens_pass
    virtual-host: /